version: "3.3"
services:
  api:
    build:
      args:
        user: ${HOST_USER_NAME} # your user in the host
        uid: ${HOST_USER_ID} # your user id in the host
      context: ./
      dockerfile: Dockerfile
    image: birra
    container_name: birra-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - birra

  db:
    image: mysql:5.7
    container_name: birra-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - birra

  nginx:
    image: nginx:alpine
    container_name: birra-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - birra

networks:
  birra:
    driver: bridge
